### PR TITLE
Adds Directory Functionality

### PR DESCRIPTION
**Pull request by Dmitri-2**
This commit introduces the following elements: user interface updates, file-system updates, and editor error checking updates. (All of which are required to support directories.)

- User interface updates include: a "Folder" button to allow the user to create directories, and a context-menu to support right-clicking directories to delete them. Both of these additions required changes to the index.html and CSS files. 

- File system updates include: correctly adjusting "current" variables to respond to directories being deleted or created. Improves error checking that is needed for proper functionality.

- Editor error checking update: adds a currentFilePath variable to local storage, so that the editor can edit files inside directories. (Previously, isChanged() would throw an exception, since it no longer had the correct file name, due to the file-path addition.)

### CODE REVIEW

**Comment by apblack** [comment]
Dmitri, I merged this, but then deleted index.html and scripts/background.js, since these files are both generated.  As a rule, generated files should not be under version control, but instead the recipe to re-generate them should be there. 

If there were actually important changes in the files that I deleted, then they should be incorporated into index.in.html, and scripts/background.in.js.

**Comment by Dmitri-2** [comment]
Thank you! Is there a mechanism to generate the index.html and background.js files? I couldn't find one in the Makefile. The command that I have been using to compile my work — "make expWebBuild" looks like it only generates scripts/setup.js. 

Overall, though, I don't think I had any important changes to those files. I added my UI elements to the index.in.html file, so they should still be there when index.html is generated. However, I would like to test the editor after re-generating these two files, just in case something goes wrong.

**Comment by apblack** [comment]
`make index.html` and make `scripts/background.js` worked for me.  If not, work with Peter to refine the Makefile.

**Comment by Dmitri-2** [comment]
Great! I think everything should be functioning properly in my updates. However, I was not able to properly build the web editor with Peter's new makefile yet (the old version works fine), so that will be one of my/our priorities on Monday.

**Comment by apblack** [comment]
> On 11 Jul 2016, at 05:01 , Dmitri M <notifications@github.com> wrote:
> 
> Great! I think everything should be functioning properly in my updates. However, I was not able to properly build the web editor with Peter's new makefile yet (the old version works fine), so that will be one of my/our priorities on Monday.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Good.  So Peter and you can work this out.  We decided to change the location of the web editor (to ~grace/ide and ~grace/dev/ide). so that will need some 
rejiggering.

It may be that you need me to put your ssh public keys into the ~grace/.ssh/authorized-keys file, so that you can log in to ~grace directly.  Everything is group writable, but that’s not always enough.

	Andrew

**Pull request merged**
